### ISSUE TITLE
no data/cath

### ISSUE THREAD

**Issue by minghuihuang** [jingraham/neurips19-graph-protein-design#1]
runfile('/Users/hmh2017/Downloads/neurips19-graph-protein-design-master/experiments/train_s2s.py', wdir='/Users/hmh2017/Downloads/neurips19-graph-protein-design-master/experiments')
Number of parameters: 1526164
Traceback (most recent call last):

  File "/Users/hmh2017/Downloads/neurips19-graph-protein-design-master/experiments/train_s2s.py", line 21, in <module>
    dataset = data.StructureDataset(args.file_data, truncate=None, max_length=500)

  File "../struct2seq/data.py", line 16, in __init__
    with open(jsonl_file) as f:

FileNotFoundError: [Errno 2] No such file or directory: '../data/cath/chain_set.jsonl'

**Comment by sirius777coder** [comment]
Hello! I meet this problem too. Do you solve it?
